### PR TITLE
support bottom type as receiver

### PR DESCRIPTION
**Pull request by ptarjan**
I had a tough time writing a test for this since I couldn't figure out how to return the bottom type from real code

### CODE REVIEW

**Comment by jeffrey-s-foster** [comment]
I'm not sure I understand this proposed change. Am I right that it makes any method call on %bot return %bot? What's the intuition behind that choice?

**Comment by ptarjan** [comment]
This was needed after https://github.com/plum-umd/rdl/pull/48 so that you can do `foo.bar.baz`. Because we typed those unknown functions as returning `%bot` we also made it infectious here. Should it be returning something else? If so we can use that here.

**Comment by jeffrey-s-foster** [comment]
Okay to drop this in favor of #53? I like #53 much better.

**Comment by ptarjan** [comment]
+1 agreed

**Pull request closed without merging**
