### PR TITLE
fix type checking of object class singleton methods (works with older Ruby versions)

### PR DESCRIPTION
**Pull request by mckaz**
Obscure error for the last one. I defined `singleton_method_added` in the Module class then used `define_method` in the Object class to define it there as well. It turns out that, in older versions of Ruby, we can only use `define_method` to bind methods to objects which come from one of the method's ancestors. Since Object is an ancestors of Module, and not vice versa, this raised an error.

Moving the definition of `singleton_method_added` to the Object class, then redefining it using `define_method` in the Module class fixes the issue.

### CODE REVIEW

**Comment by mckaz** [comment]
Hm, now it looks like rvm is erring when trying to install ruby-2.1.4? I actually received this exact issue in my private RDL fork today as well. Looking into a resolution, but not sure exactly what's wrong here...

**Comment by jeffrey-s-foster** [comment]
Weird, maybe you report this as a bug to rvm?

**Comment by mckaz** [comment]
I actually raised an issue with Travis CI, I'm not sure if it's that or rvm. I can wait on their response and raise with rvm if necessary.

**Comment by jeffrey-s-foster** [comment]
Did you get any response from travis?

**Comment by mckaz** [comment]
I didn't. Will submit an issue to rvm as well just to have all bases covered.

**Comment by ptarjan** [comment]
I saw a similar error on some of my branches around the time you pushed this. I'd suggest rerunning with

```
git commit --amend -CHEAD && git push -f
```

**Pull request merged**
