### PR TITLE
Replace Fixnum by Integer in README

### PR DESCRIPTION
**Pull request by Dorian**
Fixnum got deprecated in ruby 2.4

http://blog.bigbinary.com/2016/11/18/ruby-2-4-unifies-fixnum-and-bignum-into-integer.html

### CODE REVIEW

**Comment by jeffrey-s-foster** [comment]
Right now rdl doesn't work with 2.4 so this change isn't sensible yet. But we have an approach to making it work with 2.4 and should be able to get that fixed soon. Once that is working we'll update the readme.

**Comment by Dorian** [comment]
@jeffrey-s-foster It's backward-compatible BTW

**Comment by jeffrey-s-foster** [comment]
Sure, but then the example types in the readme won't match the types in types/core...

Anyhow, we'll get the patch in soon!

Thanks.

**Comment by jeffrey-s-foster** [comment]
The latest version in the `dev` branch now supports Ruby 2.4, and I just updated the README in that branch to replace Fixnum with Integer (fixing some spacing and a Fixnum/an Integer as appropriate). I added an acknowledgement that you suggested this fix to the change log. Thanks!

**Comment by Dorian** [comment]
Niiiiiiiice, thanks!

**Comment by Dorian** [comment]
BTW I would give you points for that if you want: http://point-project.herokuapp.com

**Comment by Dorian** [comment]
Like 30 points for instance

**Comment by jeffrey-s-foster** [comment]
You're very welcome. I'm not sure what that points thing is? I clicked on the link and just get a page that says, "There's nothing here, yet."

**Comment by Dorian** [comment]
@jeffrey-s-foster Ooops it was points-project.herokuapp.com

**Pull request closed without merging**
